### ISSUE TITLE
Videos are Muted

### ISSUE THREAD

**Issue by shakked** [ytakzk/Fusuma#55]
I'm recording videos but they do not have sounds:

```
let vc = FusumaViewController()
vc.hasVideo = true
vc.delegate = self
presentViewController(vc, animated: true, completion: nil)
```

**Comment by vic13** [comment]
I'm having the same issue. Did you manage to fix it?

**Comment by shakked** [comment]
No I did not, ended up using default `UIImagePickerController`

**Comment by cresouls** [comment]
in  FSVideoCameraView.swift , add the following code in functions  initialize and flipbuttonpressed 

```
for device in AVCaptureDevice.devicesWithMediaType(AVMediaTypeAudio) {
                    let device = device as? AVCaptureDevice
                    var audioInput = try! AVCaptureDeviceInput(device: device)
                    session.addInput(audioInput)
                }
```

**Comment by ytakzk** [comment]
@shakked Done 👍

**Comment by artemsmikh** [comment]
Is there really no way other than changing code inside the library?

**Comment by shakked** [comment]
@artemsmikh It looks like @ytakzk fixed the bug.

**Comment by artemsmikh** [comment]
@shakked I thought so but I can't find that fix anywhere.

**Comment by eddieespinal** [comment]
Can someone please put this fix in the library?  I can do a Pull request if needed.  I was able to fix it in Swift 4 using the following code changes:

```
for device in AVCaptureDevice.devices(for: AVMediaType.audio) {
                let audioInput = try! AVCaptureDeviceInput(device: device)
                session.addInput(audioInput)
 }
```

I added this inside `func initialize()` after line 96

I would love to have this added to the library so that I don't have to modify the files directly inside my project and then have issues in the future.

Thanks.
